name: base_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  commons_dependencies:
    git:
      url: https://github.com/toshiossada/microapp_commons_dependencies.git
      ref: v1.0.0
  core:
    path: '../core'
    # git:
    #   url: https://github.com/toshiossada/microapp_core.git
    #   ref: v1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.1
  flutter_modular_test: ^1.0.1
  hive_generator: ^1.1.0
  http_mock_adapter: ^0.2.1
  mockito: ^5.0.5
  triple_test: ^0.0.5  
  effective_dart: ^1.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Italic-VariableFont_wght.ttf
          style: italic
        - asset: assets/fonts/Rubik/Rubik-VariableFont_wght.ttf
        - asset: assets/fonts/Rubik/static/Rubik-Bold.ttf
          weight: 700
